# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class BrandedFoodObjectIngredients(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, chomp: str=None, usda: str=None):  # noqa: E501
        """BrandedFoodObjectIngredients - a model defined in Swagger

        :param chomp: The chomp of this BrandedFoodObjectIngredients.  # noqa: E501
        :type chomp: str
        :param usda: The usda of this BrandedFoodObjectIngredients.  # noqa: E501
        :type usda: str
        """
        self.swagger_types = {
            'chomp': str,
            'usda': str
        }

        self.attribute_map = {
            'chomp': 'chomp',
            'usda': 'usda'
        }
        self._chomp = chomp
        self._usda = usda

    @classmethod
    def from_dict(cls, dikt) -> 'BrandedFoodObjectIngredients':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BrandedFoodObject_ingredients of this BrandedFoodObjectIngredients.  # noqa: E501
        :rtype: BrandedFoodObjectIngredients
        """
        return util.deserialize_model(dikt, cls)

    @property
    def chomp(self) -> str:
        """Gets the chomp of this BrandedFoodObjectIngredients.

        Ingredients for this item from Chomp's internal database  # noqa: E501

        :return: The chomp of this BrandedFoodObjectIngredients.
        :rtype: str
        """
        return self._chomp

    @chomp.setter
    def chomp(self, chomp: str):
        """Sets the chomp of this BrandedFoodObjectIngredients.

        Ingredients for this item from Chomp's internal database  # noqa: E501

        :param chomp: The chomp of this BrandedFoodObjectIngredients.
        :type chomp: str
        """

        self._chomp = chomp

    @property
    def usda(self) -> str:
        """Gets the usda of this BrandedFoodObjectIngredients.

        This branded food item's ingredients according to the USDA  # noqa: E501

        :return: The usda of this BrandedFoodObjectIngredients.
        :rtype: str
        """
        return self._usda

    @usda.setter
    def usda(self, usda: str):
        """Sets the usda of this BrandedFoodObjectIngredients.

        This branded food item's ingredients according to the USDA  # noqa: E501

        :param usda: The usda of this BrandedFoodObjectIngredients.
        :type usda: str
        """

        self._usda = usda
