# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class BrandedFoodObjectComponents(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, pct_weight: float=None, gram_weight: float=None, is_refuse: bool=None, data_points: int=None):  # noqa: E501
        """BrandedFoodObjectComponents - a model defined in Swagger

        :param name: The name of this BrandedFoodObjectComponents.  # noqa: E501
        :type name: str
        :param pct_weight: The pct_weight of this BrandedFoodObjectComponents.  # noqa: E501
        :type pct_weight: float
        :param gram_weight: The gram_weight of this BrandedFoodObjectComponents.  # noqa: E501
        :type gram_weight: float
        :param is_refuse: The is_refuse of this BrandedFoodObjectComponents.  # noqa: E501
        :type is_refuse: bool
        :param data_points: The data_points of this BrandedFoodObjectComponents.  # noqa: E501
        :type data_points: int
        """
        self.swagger_types = {
            'name': str,
            'pct_weight': float,
            'gram_weight': float,
            'is_refuse': bool,
            'data_points': int
        }

        self.attribute_map = {
            'name': 'name',
            'pct_weight': 'pct_weight',
            'gram_weight': 'gram_weight',
            'is_refuse': 'is_refuse',
            'data_points': 'data_points'
        }
        self._name = name
        self._pct_weight = pct_weight
        self._gram_weight = gram_weight
        self._is_refuse = is_refuse
        self._data_points = data_points

    @classmethod
    def from_dict(cls, dikt) -> 'BrandedFoodObjectComponents':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BrandedFoodObject_components of this BrandedFoodObjectComponents.  # noqa: E501
        :rtype: BrandedFoodObjectComponents
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this BrandedFoodObjectComponents.

        The kind of component, e.g. bone  # noqa: E501

        :return: The name of this BrandedFoodObjectComponents.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this BrandedFoodObjectComponents.

        The kind of component, e.g. bone  # noqa: E501

        :param name: The name of this BrandedFoodObjectComponents.
        :type name: str
        """

        self._name = name

    @property
    def pct_weight(self) -> float:
        """Gets the pct_weight of this BrandedFoodObjectComponents.

        The weight of the component as a percentage of the total weight of the food  # noqa: E501

        :return: The pct_weight of this BrandedFoodObjectComponents.
        :rtype: float
        """
        return self._pct_weight

    @pct_weight.setter
    def pct_weight(self, pct_weight: float):
        """Sets the pct_weight of this BrandedFoodObjectComponents.

        The weight of the component as a percentage of the total weight of the food  # noqa: E501

        :param pct_weight: The pct_weight of this BrandedFoodObjectComponents.
        :type pct_weight: float
        """

        self._pct_weight = pct_weight

    @property
    def gram_weight(self) -> float:
        """Gets the gram_weight of this BrandedFoodObjectComponents.

        The weight of the component in grams  # noqa: E501

        :return: The gram_weight of this BrandedFoodObjectComponents.
        :rtype: float
        """
        return self._gram_weight

    @gram_weight.setter
    def gram_weight(self, gram_weight: float):
        """Sets the gram_weight of this BrandedFoodObjectComponents.

        The weight of the component in grams  # noqa: E501

        :param gram_weight: The gram_weight of this BrandedFoodObjectComponents.
        :type gram_weight: float
        """

        self._gram_weight = gram_weight

    @property
    def is_refuse(self) -> bool:
        """Gets the is_refuse of this BrandedFoodObjectComponents.

        Whether the component is refuse, i.e. not edible  # noqa: E501

        :return: The is_refuse of this BrandedFoodObjectComponents.
        :rtype: bool
        """
        return self._is_refuse

    @is_refuse.setter
    def is_refuse(self, is_refuse: bool):
        """Sets the is_refuse of this BrandedFoodObjectComponents.

        Whether the component is refuse, i.e. not edible  # noqa: E501

        :param is_refuse: The is_refuse of this BrandedFoodObjectComponents.
        :type is_refuse: bool
        """

        self._is_refuse = is_refuse

    @property
    def data_points(self) -> int:
        """Gets the data_points of this BrandedFoodObjectComponents.

        The number of obersvations on which the measure is based  # noqa: E501

        :return: The data_points of this BrandedFoodObjectComponents.
        :rtype: int
        """
        return self._data_points

    @data_points.setter
    def data_points(self, data_points: int):
        """Sets the data_points of this BrandedFoodObjectComponents.

        The number of obersvations on which the measure is based  # noqa: E501

        :param data_points: The data_points of this BrandedFoodObjectComponents.
        :type data_points: int
        """

        self._data_points = data_points
