# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class BrandedFoodObjectServingUsda(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, size: str=None, measurement_unit: str=None, size_fulltext: str=None):  # noqa: E501
        """BrandedFoodObjectServingUsda - a model defined in Swagger

        :param size: The size of this BrandedFoodObjectServingUsda.  # noqa: E501
        :type size: str
        :param measurement_unit: The measurement_unit of this BrandedFoodObjectServingUsda.  # noqa: E501
        :type measurement_unit: str
        :param size_fulltext: The size_fulltext of this BrandedFoodObjectServingUsda.  # noqa: E501
        :type size_fulltext: str
        """
        self.swagger_types = {
            'size': str,
            'measurement_unit': str,
            'size_fulltext': str
        }

        self.attribute_map = {
            'size': 'size',
            'measurement_unit': 'measurement_unit',
            'size_fulltext': 'size_fulltext'
        }
        self._size = size
        self._measurement_unit = measurement_unit
        self._size_fulltext = size_fulltext

    @classmethod
    def from_dict(cls, dikt) -> 'BrandedFoodObjectServingUsda':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BrandedFoodObject_serving_usda of this BrandedFoodObjectServingUsda.  # noqa: E501
        :rtype: BrandedFoodObjectServingUsda
        """
        return util.deserialize_model(dikt, cls)

    @property
    def size(self) -> str:
        """Gets the size of this BrandedFoodObjectServingUsda.

        Serving size  # noqa: E501

        :return: The size of this BrandedFoodObjectServingUsda.
        :rtype: str
        """
        return self._size

    @size.setter
    def size(self, size: str):
        """Sets the size of this BrandedFoodObjectServingUsda.

        Serving size  # noqa: E501

        :param size: The size of this BrandedFoodObjectServingUsda.
        :type size: str
        """

        self._size = size

    @property
    def measurement_unit(self) -> str:
        """Gets the measurement_unit of this BrandedFoodObjectServingUsda.

        Measurement unit for each serving (e.g. if measure is 3 tsp, the unit is tsp)  # noqa: E501

        :return: The measurement_unit of this BrandedFoodObjectServingUsda.
        :rtype: str
        """
        return self._measurement_unit

    @measurement_unit.setter
    def measurement_unit(self, measurement_unit: str):
        """Sets the measurement_unit of this BrandedFoodObjectServingUsda.

        Measurement unit for each serving (e.g. if measure is 3 tsp, the unit is tsp)  # noqa: E501

        :param measurement_unit: The measurement_unit of this BrandedFoodObjectServingUsda.
        :type measurement_unit: str
        """

        self._measurement_unit = measurement_unit

    @property
    def size_fulltext(self) -> str:
        """Gets the size_fulltext of this BrandedFoodObjectServingUsda.

        Serving size description  # noqa: E501

        :return: The size_fulltext of this BrandedFoodObjectServingUsda.
        :rtype: str
        """
        return self._size_fulltext

    @size_fulltext.setter
    def size_fulltext(self, size_fulltext: str):
        """Sets the size_fulltext of this BrandedFoodObjectServingUsda.

        Serving size description  # noqa: E501

        :param size_fulltext: The size_fulltext of this BrandedFoodObjectServingUsda.
        :type size_fulltext: str
        """

        self._size_fulltext = size_fulltext
