# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class BrandedFoodObjectServingChomp(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, size: str=None):  # noqa: E501
        """BrandedFoodObjectServingChomp - a model defined in Swagger

        :param size: The size of this BrandedFoodObjectServingChomp.  # noqa: E501
        :type size: str
        """
        self.swagger_types = {
            'size': str
        }

        self.attribute_map = {
            'size': 'size'
        }
        self._size = size

    @classmethod
    def from_dict(cls, dikt) -> 'BrandedFoodObjectServingChomp':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BrandedFoodObject_serving_chomp of this BrandedFoodObjectServingChomp.  # noqa: E501
        :rtype: BrandedFoodObjectServingChomp
        """
        return util.deserialize_model(dikt, cls)

    @property
    def size(self) -> str:
        """Gets the size of this BrandedFoodObjectServingChomp.

        Serving size with measurement unit (e.g. if measure is 3 tsp, the unit is tsp)  # noqa: E501

        :return: The size of this BrandedFoodObjectServingChomp.
        :rtype: str
        """
        return self._size

    @size.setter
    def size(self, size: str):
        """Sets the size of this BrandedFoodObjectServingChomp.

        Serving size with measurement unit (e.g. if measure is 3 tsp, the unit is tsp)  # noqa: E501

        :param size: The size of this BrandedFoodObjectServingChomp.
        :type size: str
        """

        self._size = size
