# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class BrandedFoodObjectPackagingPhotosIngredients(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, small: str=None, thumb: str=None, display: str=None):  # noqa: E501
        """BrandedFoodObjectPackagingPhotosIngredients - a model defined in Swagger

        :param small: The small of this BrandedFoodObjectPackagingPhotosIngredients.  # noqa: E501
        :type small: str
        :param thumb: The thumb of this BrandedFoodObjectPackagingPhotosIngredients.  # noqa: E501
        :type thumb: str
        :param display: The display of this BrandedFoodObjectPackagingPhotosIngredients.  # noqa: E501
        :type display: str
        """
        self.swagger_types = {
            'small': str,
            'thumb': str,
            'display': str
        }

        self.attribute_map = {
            'small': 'small',
            'thumb': 'thumb',
            'display': 'display'
        }
        self._small = small
        self._thumb = thumb
        self._display = display

    @classmethod
    def from_dict(cls, dikt) -> 'BrandedFoodObjectPackagingPhotosIngredients':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BrandedFoodObject_packaging_photos_ingredients of this BrandedFoodObjectPackagingPhotosIngredients.  # noqa: E501
        :rtype: BrandedFoodObjectPackagingPhotosIngredients
        """
        return util.deserialize_model(dikt, cls)

    @property
    def small(self) -> str:
        """Gets the small of this BrandedFoodObjectPackagingPhotosIngredients.

        Small photo of the ingredients on this item's packaging  # noqa: E501

        :return: The small of this BrandedFoodObjectPackagingPhotosIngredients.
        :rtype: str
        """
        return self._small

    @small.setter
    def small(self, small: str):
        """Sets the small of this BrandedFoodObjectPackagingPhotosIngredients.

        Small photo of the ingredients on this item's packaging  # noqa: E501

        :param small: The small of this BrandedFoodObjectPackagingPhotosIngredients.
        :type small: str
        """

        self._small = small

    @property
    def thumb(self) -> str:
        """Gets the thumb of this BrandedFoodObjectPackagingPhotosIngredients.

        Thumbnail photo of the ingredients on this item's packaging  # noqa: E501

        :return: The thumb of this BrandedFoodObjectPackagingPhotosIngredients.
        :rtype: str
        """
        return self._thumb

    @thumb.setter
    def thumb(self, thumb: str):
        """Sets the thumb of this BrandedFoodObjectPackagingPhotosIngredients.

        Thumbnail photo of the ingredients on this item's packaging  # noqa: E501

        :param thumb: The thumb of this BrandedFoodObjectPackagingPhotosIngredients.
        :type thumb: str
        """

        self._thumb = thumb

    @property
    def display(self) -> str:
        """Gets the display of this BrandedFoodObjectPackagingPhotosIngredients.

        Full-sized photo of the ingredients on this item's packaging  # noqa: E501

        :return: The display of this BrandedFoodObjectPackagingPhotosIngredients.
        :rtype: str
        """
        return self._display

    @display.setter
    def display(self, display: str):
        """Sets the display of this BrandedFoodObjectPackagingPhotosIngredients.

        Full-sized photo of the ingredients on this item's packaging  # noqa: E501

        :param display: The display of this BrandedFoodObjectPackagingPhotosIngredients.
        :type display: str
        """

        self._display = display
