# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class BrandedFoodObjectPortions(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, measurement_unit: str=None, description: str=None, modifier: str=None, gram_weight: float=None, data_points: int=None, footnote: str=None):  # noqa: E501
        """BrandedFoodObjectPortions - a model defined in Swagger

        :param measurement_unit: The measurement_unit of this BrandedFoodObjectPortions.  # noqa: E501
        :type measurement_unit: str
        :param description: The description of this BrandedFoodObjectPortions.  # noqa: E501
        :type description: str
        :param modifier: The modifier of this BrandedFoodObjectPortions.  # noqa: E501
        :type modifier: str
        :param gram_weight: The gram_weight of this BrandedFoodObjectPortions.  # noqa: E501
        :type gram_weight: float
        :param data_points: The data_points of this BrandedFoodObjectPortions.  # noqa: E501
        :type data_points: int
        :param footnote: The footnote of this BrandedFoodObjectPortions.  # noqa: E501
        :type footnote: str
        """
        self.swagger_types = {
            'measurement_unit': str,
            'description': str,
            'modifier': str,
            'gram_weight': float,
            'data_points': int,
            'footnote': str
        }

        self.attribute_map = {
            'measurement_unit': 'measurement_unit',
            'description': 'description',
            'modifier': 'modifier',
            'gram_weight': 'gram_weight',
            'data_points': 'data_points',
            'footnote': 'footnote'
        }
        self._measurement_unit = measurement_unit
        self._description = description
        self._modifier = modifier
        self._gram_weight = gram_weight
        self._data_points = data_points
        self._footnote = footnote

    @classmethod
    def from_dict(cls, dikt) -> 'BrandedFoodObjectPortions':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BrandedFoodObject_portions of this BrandedFoodObjectPortions.  # noqa: E501
        :rtype: BrandedFoodObjectPortions
        """
        return util.deserialize_model(dikt, cls)

    @property
    def measurement_unit(self) -> str:
        """Gets the measurement_unit of this BrandedFoodObjectPortions.

        The unit used for measure (e.g. if mesure is 3 tsp, the unit is tsp)  # noqa: E501

        :return: The measurement_unit of this BrandedFoodObjectPortions.
        :rtype: str
        """
        return self._measurement_unit

    @measurement_unit.setter
    def measurement_unit(self, measurement_unit: str):
        """Sets the measurement_unit of this BrandedFoodObjectPortions.

        The unit used for measure (e.g. if mesure is 3 tsp, the unit is tsp)  # noqa: E501

        :param measurement_unit: The measurement_unit of this BrandedFoodObjectPortions.
        :type measurement_unit: str
        """

        self._measurement_unit = measurement_unit

    @property
    def description(self) -> str:
        """Gets the description of this BrandedFoodObjectPortions.

        Comments that provide more specificity on the measure. For example, for a pizza measure the dissemination text might be 1 slice is 1/8th of a 14 inch pizza.  # noqa: E501

        :return: The description of this BrandedFoodObjectPortions.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this BrandedFoodObjectPortions.

        Comments that provide more specificity on the measure. For example, for a pizza measure the dissemination text might be 1 slice is 1/8th of a 14 inch pizza.  # noqa: E501

        :param description: The description of this BrandedFoodObjectPortions.
        :type description: str
        """

        self._description = description

    @property
    def modifier(self) -> str:
        """Gets the modifier of this BrandedFoodObjectPortions.

        Qualifier of the measure (e.g. related to food shape or form) (e.g. melted, crushed, diced)  # noqa: E501

        :return: The modifier of this BrandedFoodObjectPortions.
        :rtype: str
        """
        return self._modifier

    @modifier.setter
    def modifier(self, modifier: str):
        """Sets the modifier of this BrandedFoodObjectPortions.

        Qualifier of the measure (e.g. related to food shape or form) (e.g. melted, crushed, diced)  # noqa: E501

        :param modifier: The modifier of this BrandedFoodObjectPortions.
        :type modifier: str
        """

        self._modifier = modifier

    @property
    def gram_weight(self) -> float:
        """Gets the gram_weight of this BrandedFoodObjectPortions.

        The weight of the measure in grams  # noqa: E501

        :return: The gram_weight of this BrandedFoodObjectPortions.
        :rtype: float
        """
        return self._gram_weight

    @gram_weight.setter
    def gram_weight(self, gram_weight: float):
        """Sets the gram_weight of this BrandedFoodObjectPortions.

        The weight of the measure in grams  # noqa: E501

        :param gram_weight: The gram_weight of this BrandedFoodObjectPortions.
        :type gram_weight: float
        """

        self._gram_weight = gram_weight

    @property
    def data_points(self) -> int:
        """Gets the data_points of this BrandedFoodObjectPortions.

        The number of observations on which the measure is based  # noqa: E501

        :return: The data_points of this BrandedFoodObjectPortions.
        :rtype: int
        """
        return self._data_points

    @data_points.setter
    def data_points(self, data_points: int):
        """Sets the data_points of this BrandedFoodObjectPortions.

        The number of observations on which the measure is based  # noqa: E501

        :param data_points: The data_points of this BrandedFoodObjectPortions.
        :type data_points: int
        """

        self._data_points = data_points

    @property
    def footnote(self) -> str:
        """Gets the footnote of this BrandedFoodObjectPortions.

        Comments on any unusual aspects of the measure. Examples might includes caveats on the usage of a measure, or reasons why a measure gram weight is an unexpected value.  # noqa: E501

        :return: The footnote of this BrandedFoodObjectPortions.
        :rtype: str
        """
        return self._footnote

    @footnote.setter
    def footnote(self, footnote: str):
        """Sets the footnote of this BrandedFoodObjectPortions.

        Comments on any unusual aspects of the measure. Examples might includes caveats on the usage of a measure, or reasons why a measure gram weight is an unexpected value.  # noqa: E501

        :param footnote: The footnote of this BrandedFoodObjectPortions.
        :type footnote: str
        """

        self._footnote = footnote
