# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.branded_food_object_serving_chomp import BrandedFoodObjectServingChomp  # noqa: F401,E501
from swagger_server.models.branded_food_object_serving_usda import BrandedFoodObjectServingUsda  # noqa: F401,E501
from swagger_server import util


class BrandedFoodObjectServing(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, chomp: BrandedFoodObjectServingChomp=None, usda: BrandedFoodObjectServingUsda=None):  # noqa: E501
        """BrandedFoodObjectServing - a model defined in Swagger

        :param chomp: The chomp of this BrandedFoodObjectServing.  # noqa: E501
        :type chomp: BrandedFoodObjectServingChomp
        :param usda: The usda of this BrandedFoodObjectServing.  # noqa: E501
        :type usda: BrandedFoodObjectServingUsda
        """
        self.swagger_types = {
            'chomp': BrandedFoodObjectServingChomp,
            'usda': BrandedFoodObjectServingUsda
        }

        self.attribute_map = {
            'chomp': 'chomp',
            'usda': 'usda'
        }
        self._chomp = chomp
        self._usda = usda

    @classmethod
    def from_dict(cls, dikt) -> 'BrandedFoodObjectServing':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BrandedFoodObject_serving of this BrandedFoodObjectServing.  # noqa: E501
        :rtype: BrandedFoodObjectServing
        """
        return util.deserialize_model(dikt, cls)

    @property
    def chomp(self) -> BrandedFoodObjectServingChomp:
        """Gets the chomp of this BrandedFoodObjectServing.


        :return: The chomp of this BrandedFoodObjectServing.
        :rtype: BrandedFoodObjectServingChomp
        """
        return self._chomp

    @chomp.setter
    def chomp(self, chomp: BrandedFoodObjectServingChomp):
        """Sets the chomp of this BrandedFoodObjectServing.


        :param chomp: The chomp of this BrandedFoodObjectServing.
        :type chomp: BrandedFoodObjectServingChomp
        """

        self._chomp = chomp

    @property
    def usda(self) -> BrandedFoodObjectServingUsda:
        """Gets the usda of this BrandedFoodObjectServing.


        :return: The usda of this BrandedFoodObjectServing.
        :rtype: BrandedFoodObjectServingUsda
        """
        return self._usda

    @usda.setter
    def usda(self, usda: BrandedFoodObjectServingUsda):
        """Sets the usda of this BrandedFoodObjectServing.


        :param usda: The usda of this BrandedFoodObjectServing.
        :type usda: BrandedFoodObjectServingUsda
        """

        self._usda = usda
