# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class BrandedFoodObjectPackage(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, quantity: int=None, size: int=None):  # noqa: E501
        """BrandedFoodObjectPackage - a model defined in Swagger

        :param quantity: The quantity of this BrandedFoodObjectPackage.  # noqa: E501
        :type quantity: int
        :param size: The size of this BrandedFoodObjectPackage.  # noqa: E501
        :type size: int
        """
        self.swagger_types = {
            'quantity': int,
            'size': int
        }

        self.attribute_map = {
            'quantity': 'quantity',
            'size': 'size'
        }
        self._quantity = quantity
        self._size = size

    @classmethod
    def from_dict(cls, dikt) -> 'BrandedFoodObjectPackage':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BrandedFoodObject_package of this BrandedFoodObjectPackage.  # noqa: E501
        :rtype: BrandedFoodObjectPackage
        """
        return util.deserialize_model(dikt, cls)

    @property
    def quantity(self) -> int:
        """Gets the quantity of this BrandedFoodObjectPackage.

        Package quantity  # noqa: E501

        :return: The quantity of this BrandedFoodObjectPackage.
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity: int):
        """Sets the quantity of this BrandedFoodObjectPackage.

        Package quantity  # noqa: E501

        :param quantity: The quantity of this BrandedFoodObjectPackage.
        :type quantity: int
        """

        self._quantity = quantity

    @property
    def size(self) -> int:
        """Gets the size of this BrandedFoodObjectPackage.

        Package size  # noqa: E501

        :return: The size of this BrandedFoodObjectPackage.
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size: int):
        """Sets the size of this BrandedFoodObjectPackage.

        Package size  # noqa: E501

        :param size: The size of this BrandedFoodObjectPackage.
        :type size: int
        """

        self._size = size
