# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.ingredient_object_items import IngredientObjectItems  # noqa: F401,E501
from swagger_server import util


class IngredientObject(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, items: List[IngredientObjectItems]=None):  # noqa: E501
        """IngredientObject - a model defined in Swagger

        :param items: The items of this IngredientObject.  # noqa: E501
        :type items: List[IngredientObjectItems]
        """
        self.swagger_types = {
            'items': List[IngredientObjectItems]
        }

        self.attribute_map = {
            'items': 'items'
        }
        self._items = items

    @classmethod
    def from_dict(cls, dikt) -> 'IngredientObject':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The IngredientObject of this IngredientObject.  # noqa: E501
        :rtype: IngredientObject
        """
        return util.deserialize_model(dikt, cls)

    @property
    def items(self) -> List[IngredientObjectItems]:
        """Gets the items of this IngredientObject.

        An array containing an object for each individual item returned by your API call.  # noqa: E501

        :return: The items of this IngredientObject.
        :rtype: List[IngredientObjectItems]
        """
        return self._items

    @items.setter
    def items(self, items: List[IngredientObjectItems]):
        """Sets the items of this IngredientObject.

        An array containing an object for each individual item returned by your API call.  # noqa: E501

        :param items: The items of this IngredientObject.
        :type items: List[IngredientObjectItems]
        """

        self._items = items
