# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.branded_food_object_nutrients_usda import BrandedFoodObjectNutrientsUsda  # noqa: F401,E501
from swagger_server import util


class IngredientObjectNutrients(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, usda: List[BrandedFoodObjectNutrientsUsda]=None):  # noqa: E501
        """IngredientObjectNutrients - a model defined in Swagger

        :param usda: The usda of this IngredientObjectNutrients.  # noqa: E501
        :type usda: List[BrandedFoodObjectNutrientsUsda]
        """
        self.swagger_types = {
            'usda': List[BrandedFoodObjectNutrientsUsda]
        }

        self.attribute_map = {
            'usda': 'usda'
        }
        self._usda = usda

    @classmethod
    def from_dict(cls, dikt) -> 'IngredientObjectNutrients':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The IngredientObject_nutrients of this IngredientObjectNutrients.  # noqa: E501
        :rtype: IngredientObjectNutrients
        """
        return util.deserialize_model(dikt, cls)

    @property
    def usda(self) -> List[BrandedFoodObjectNutrientsUsda]:
        """Gets the usda of this IngredientObjectNutrients.

        An array containing an object for each nutrient data point as found in the USDA database  # noqa: E501

        :return: The usda of this IngredientObjectNutrients.
        :rtype: List[BrandedFoodObjectNutrientsUsda]
        """
        return self._usda

    @usda.setter
    def usda(self, usda: List[BrandedFoodObjectNutrientsUsda]):
        """Sets the usda of this IngredientObjectNutrients.

        An array containing an object for each nutrient data point as found in the USDA database  # noqa: E501

        :param usda: The usda of this IngredientObjectNutrients.
        :type usda: List[BrandedFoodObjectNutrientsUsda]
        """

        self._usda = usda
