# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RecipeObjectNutrientsCalories(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, title: str=None, value: str=None, percent: str=None):  # noqa: E501
        """RecipeObjectNutrientsCalories - a model defined in Swagger

        :param title: The title of this RecipeObjectNutrientsCalories.  # noqa: E501
        :type title: str
        :param value: The value of this RecipeObjectNutrientsCalories.  # noqa: E501
        :type value: str
        :param percent: The percent of this RecipeObjectNutrientsCalories.  # noqa: E501
        :type percent: str
        """
        self.swagger_types = {
            'title': str,
            'value': str,
            'percent': str
        }

        self.attribute_map = {
            'title': 'title',
            'value': 'value',
            'percent': 'percent'
        }
        self._title = title
        self._value = value
        self._percent = percent

    @classmethod
    def from_dict(cls, dikt) -> 'RecipeObjectNutrientsCalories':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RecipeObject_nutrients_calories of this RecipeObjectNutrientsCalories.  # noqa: E501
        :rtype: RecipeObjectNutrientsCalories
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title(self) -> str:
        """Gets the title of this RecipeObjectNutrientsCalories.

        Nutrient name  # noqa: E501

        :return: The title of this RecipeObjectNutrientsCalories.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this RecipeObjectNutrientsCalories.

        Nutrient name  # noqa: E501

        :param title: The title of this RecipeObjectNutrientsCalories.
        :type title: str
        """

        self._title = title

    @property
    def value(self) -> str:
        """Gets the value of this RecipeObjectNutrientsCalories.

        The amount of this nutrient in this recipe  # noqa: E501

        :return: The value of this RecipeObjectNutrientsCalories.
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value: str):
        """Sets the value of this RecipeObjectNutrientsCalories.

        The amount of this nutrient in this recipe  # noqa: E501

        :param value: The value of this RecipeObjectNutrientsCalories.
        :type value: str
        """

        self._value = value

    @property
    def percent(self) -> str:
        """Gets the percent of this RecipeObjectNutrientsCalories.

        The daily recommended percent total for this nutrient  # noqa: E501

        :return: The percent of this RecipeObjectNutrientsCalories.
        :rtype: str
        """
        return self._percent

    @percent.setter
    def percent(self, percent: str):
        """Sets the percent of this RecipeObjectNutrientsCalories.

        The daily recommended percent total for this nutrient  # noqa: E501

        :param percent: The percent of this RecipeObjectNutrientsCalories.
        :type percent: str
        """

        self._percent = percent
