# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RecipeObjectIngredients(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, quantity: str=None, description: str=None):  # noqa: E501
        """RecipeObjectIngredients - a model defined in Swagger

        :param quantity: The quantity of this RecipeObjectIngredients.  # noqa: E501
        :type quantity: str
        :param description: The description of this RecipeObjectIngredients.  # noqa: E501
        :type description: str
        """
        self.swagger_types = {
            'quantity': str,
            'description': str
        }

        self.attribute_map = {
            'quantity': 'quantity',
            'description': 'description'
        }
        self._quantity = quantity
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'RecipeObjectIngredients':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RecipeObject_ingredients of this RecipeObjectIngredients.  # noqa: E501
        :rtype: RecipeObjectIngredients
        """
        return util.deserialize_model(dikt, cls)

    @property
    def quantity(self) -> str:
        """Gets the quantity of this RecipeObjectIngredients.

        The quantity of this ingredient  # noqa: E501

        :return: The quantity of this RecipeObjectIngredients.
        :rtype: str
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity: str):
        """Sets the quantity of this RecipeObjectIngredients.

        The quantity of this ingredient  # noqa: E501

        :param quantity: The quantity of this RecipeObjectIngredients.
        :type quantity: str
        """

        self._quantity = quantity

    @property
    def description(self) -> str:
        """Gets the description of this RecipeObjectIngredients.

        A description of this ingredient  # noqa: E501

        :return: The description of this RecipeObjectIngredients.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this RecipeObjectIngredients.

        A description of this ingredient  # noqa: E501

        :param description: The description of this RecipeObjectIngredients.
        :type description: str
        """

        self._description = description
