# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.recipe_object_items import RecipeObjectItems  # noqa: F401,E501
from swagger_server import util


class RecipeObject(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, items: List[RecipeObjectItems]=None):  # noqa: E501
        """RecipeObject - a model defined in Swagger

        :param items: The items of this RecipeObject.  # noqa: E501
        :type items: List[RecipeObjectItems]
        """
        self.swagger_types = {
            'items': List[RecipeObjectItems]
        }

        self.attribute_map = {
            'items': 'items'
        }
        self._items = items

    @classmethod
    def from_dict(cls, dikt) -> 'RecipeObject':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RecipeObject of this RecipeObject.  # noqa: E501
        :rtype: RecipeObject
        """
        return util.deserialize_model(dikt, cls)

    @property
    def items(self) -> List[RecipeObjectItems]:
        """Gets the items of this RecipeObject.

        An array containing an object for each individual item returned by your API call.  # noqa: E501

        :return: The items of this RecipeObject.
        :rtype: List[RecipeObjectItems]
        """
        return self._items

    @items.setter
    def items(self, items: List[RecipeObjectItems]):
        """Sets the items of this RecipeObject.

        An array containing an object for each individual item returned by your API call.  # noqa: E501

        :param items: The items of this RecipeObject.
        :type items: List[RecipeObjectItems]
        """

        self._items = items
